# Generated by Django 4.2.9 on 2024-01-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('scale', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Small'), (2, 'Medium'), (3, 'Large')], default=0)),
            ],
        ),
    ]
